// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Category struct {
	ID   interface{}
	Name string
}

type Post struct {
	ID          interface{}
	Title       string
	Content     string
	Description string
	Link        string
	PublishedOn time.Time
}

type PostCategory struct {
	PostID     interface{}
	CategoryID interface{}
}
