// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addPostCategory = `-- name: AddPostCategory :exec
INSERT INTO post_categories (post_id, category_id)
VALUES (?, ?)
`

type AddPostCategoryParams struct {
	PostID     interface{}
	CategoryID interface{}
}

func (q *Queries) AddPostCategory(ctx context.Context, arg AddPostCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addPostCategory, arg.PostID, arg.CategoryID)
	return err
}

const createCategory = `-- name: CreateCategory :execresult
INSERT INTO categories (id, name)
VALUES (?, ?)
`

type CreateCategoryParams struct {
	ID   interface{}
	Name string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCategory, arg.ID, arg.Name)
}

const createPost = `-- name: CreatePost :execresult

INSERT INTO posts (id, title, content, description, link, published_on)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreatePostParams struct {
	ID          interface{}
	Title       string
	Content     string
	Description string
	Link        string
	PublishedOn time.Time
}

// queries.sql
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Description,
		arg.Link,
		arg.PublishedOn,
	)
}

const getCategory = `-- name: GetCategory :one
SELECT id, name FROM categories WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id interface{}) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCategoryPosts = `-- name: GetCategoryPosts :many
SELECT p.id, p.title, p.content, p.description, p.link, p.published_on FROM posts p
JOIN post_categories pc ON p.id = pc.post_id
WHERE pc.category_id = ?
`

func (q *Queries) GetCategoryPosts(ctx context.Context, categoryID interface{}) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryPosts, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Description,
			&i.Link,
			&i.PublishedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPost = `-- name: GetPost :one
SELECT id, title, content, description, link, published_on FROM posts WHERE id = ?
`

func (q *Queries) GetPost(ctx context.Context, id interface{}) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Description,
		&i.Link,
		&i.PublishedOn,
	)
	return i, err
}

const getPostCategories = `-- name: GetPostCategories :many
SELECT c.id, c.name FROM categories c
JOIN post_categories pc ON c.id = pc.category_id
WHERE pc.post_id = ?
`

func (q *Queries) GetPostCategories(ctx context.Context, postID interface{}) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getPostCategories, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name FROM categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, content, description, link, published_on FROM posts ORDER BY published_on DESC LIMIT ?
`

func (q *Queries) ListPosts(ctx context.Context, limit int64) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Description,
			&i.Link,
			&i.PublishedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
