name: Deploy Go HTMX App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

      - name: Build Docker image
        run: docker build -t gomex:latest .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: |
          docker tag gomex:latest nspielman/gomex:latest
          docker push nspielman/gomex:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install cloudflared
        run: |
          curl -L https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-archive-keyring.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-archive-keyring.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt update
          sudo apt-get install -y cloudflared

      - name: Test cloudflared installation
        run: |
          which cloudflared
          whereis cloudflared
          cloudflared --version

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Deploy to Ubuntu VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          EDGEDB_INSTANCE: ${{ secrets.EDGEDB_INSTANCE }}
          EDGEDB_SECRET_KEY: ${{ secrets.EDGEDB_SECRET_KEY }}
          CLOUDFLARE_CERT: ${{ secrets.CLOUDFLARE_CERT }}
          TUNNEL_HOSTNAME: ${{ secrets.TUNNEL_HOSTNAME }}
          CLOUDFLARE_ACCESS_CLIENT_ID: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_ID }}
          CLOUDFLARE_ACCESS_CLIENT_SECRET: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_SECRET }}

        run: |
          # Start SSH agent and add the private key
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

          # Set up known_hosts and cloudflare certificate
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan "$SSH_HOST" > ~/.ssh/known_hosts

          # Debugging: Check the contents of known_hosts
          echo "Known hosts:"
          cat ~/.ssh/known_hosts

          # Debugging: Check the values of environment variables
          echo "SSH_HOST: $SSH_HOST"
          echo "TUNNEL_HOSTNAME: $TUNNEL_HOSTNAME"

          # Additional Debugging: Resolve the hostname
          echo "Resolving SSH_HOST:"
          nslookup "$SSH_HOST"
          echo "Resolving TUNNEL_HOSTNAME:"
          nslookup "$TUNNEL_HOSTNAME"

          mkdir -p ~/.cloudflare
          echo "$CLOUDFLARE_CERT" > ~/.cloudflare/cert.pem

          # Authenticate with Cloudflare Access
          cloudflared access login --url https://$TUNNEL_HOSTNAME --client-id $CLOUDFLARE_ACCESS_CLIENT_ID --client-secret $CLOUDFLARE_ACCESS_CLIENT_SECRET

          # Use cloudflared to establish the connection and deploy the application
          ssh -o "ProxyCommand=cloudflared access ssh --hostname $TUNNEL_HOSTNAME" $SSH_USER@$SSH_HOST << 'EOF'
            docker pull nspielman/gomex:latest
            docker stop gomex || true
            docker rm gomex || true
            docker run -d --name gomex -p 80:80 \
              nspielman/gomex:latest
            export EDGEDB_INSTANCE="$EDGEDB_INSTANCE"
            export EDGEDB_SECRET_KEY="$EDGEDB_SECRET_KEY"
            export GO_ENV=production
            export PORT=80
          EOF
